version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=law_tugas1
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-server
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data:
